manage gcc test fail

diff --git a/bbbuilder b/bbbuilder
--- a/bbbuilder
+++ b/bbbuilder
@@ -96,7 +96,13 @@ function bbb_enable_gcc_custom () {
 	[ "$?" -eq 0 ] && echo "OK" || echo "Error"
 	echo "Testing ${CXX}: "
 	${BBB_CHROOTPATH}/usr/bin/${CXX} -v
-	[ "$?" -eq 0 ] && echo "OK" || echo "Error"
+	if [ "$?" -eq 0 ]
+	then
+		echo "OK"
+	else
+		echo "Error"
+		exit 1
+	fi
 	echo "Done."
 }
 
@@ -271,7 +277,7 @@ function bbb_build () {
 	bbb_download
 	bbb_mount resizeimage
 	test ${CCACHE_ENABLED} -eq 1 && bbb_enable_ccache
-	test -z "${GCC_CUSTOM[name]}" || bbb_enable_gcc_custom
+	test ! -z "${GCC_CUSTOM[name]}" && bbb_enable_gcc_custom || exit 1
 	bbb_addheader
 	# Run the batch in chrooted environment
 	echo -n "Running ${BATCHFILE} to build. Log file in ${BBBLOG_PATH}/${BUILD_LOGNAME}..."
